version: '3.3'
services:
  frontend:
    image: ivanyukvl/foodgram_frontend
    volumes:
      - frontend_volume:/app/result_build/
      - docs_volume:/app/result_docs/
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - docs_volume:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
volumes:
  frontend_volume:
  docs_volume:
