version: '3.3'
services:
  frontend:
    image: ivanyukvl/foodgram_frontend
    volumes:
      - frontend_volume:/app/result_build/
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ivanyukvl/foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static_/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - static_volume:/var/html/static_/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
      - web
volumes:
  frontend_volume:
  static_volume:
  media_volume:
