# Generated by Django 2.2.16 on 2022-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='название')),
                ('measurement_unit', models.CharField(max_length=254, verbose_name='единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='название')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='метка')),
            ],
        ),
    ]
